tools/uzem/avr8.cpp

@uze6666 According to the datasheet, TOV1 needs to be written immediately, and we need to OR any new bit flags we set that cycle, otherwise we'll blow away any immediate change that also happened to TIFR1 that cycle (such as the clearing of the interrupt flag, which would cause a duplicate interrupt and a double-increment of the scanline count, causing us to miss the first scanline).
For more information, see: http://uzebox.org/forums/viewtopic.php?f=9&t=2274&p=16125#p16125

Fix dropped scanline, while maintaining cycle-perfectness

---

tools/uzem/Makefile
tools/uzem/avr8.cpp
tools/uzem/avr8.h
tools/uzem/avr_inst_table.txt

The quest for performance as completed.
I tried to be descriptive in my commit messages, so hopefully they can be followed. There are many changes in here, looks more than really, mostly due to the instruction decoder's rearrangement. I mostly didn't touch the actual instruction codes, only as necessary to integrate them. The change of the flag logic resulted the most notable intrusion, that every instruction operating the flags now has a call to a clear macro.
Comments were also added describing components of the code, also including some TODO notes where I discovered problems with the original code. Most notably there might be timing issues regarding interrupts even in the original, which might expose with AVR code relying on certain edge cases. I didn't attempt to fix these (since I …

Uzem140 hacks

---

tools/uzem/Makefile
tools/uzem/avr8.cpp
tools/uzem/uzem.cpp

I found out how to pass arguments to an Emscripten build from the generated .html file, so the changes required to support compiling with Emscripten ended up being pretty minimal, so I conditionalized them in both the code and in the Makefile
If the EMSCRIPTEN_BUILD line is commented out in the Makefile (which it is by default) then the other EMSCRIPTEN_* variables will default to nothing, so it won't actually change the behavior of the non-Emscripten builds, even those variables appear in various other places. (The places where I put spaces, and the places where I didn't put spaces was intentional and is required, so please don't change any of the spacing.)
I figured that this was the least invasive approach, since it still allows for a debug and release version of the Emscripten builds …

Add (optional) Emscripten support by setting a flag in the Makefile

---

tools/uzem/SDEmulator.cpp
tools/uzem/SDEmulator.h
tools/uzem/avr8.cpp
tools/uzem/gdbserver.cpp
tools/uzem/gdbserver.h
tools/uzem/uzem.cpp
tools/uzem/uzerom.cpp

This allows Uzem to be properly built using clang++ rather than g++,
which allow games that use the SD card to run properly when built for
the web using Emscripten.

Fix all warnings except the sign comparison ones. (Allows web-based Uzem to play ROMs that use SD card)

---

tools/uzem/Makefile
tools/uzem/avr8.cpp
tools/uzem/avr8.h
tools/uzem/uzem.cpp

* Fix screenshots so they are back to being 630x448, rather than 720x224.
* Add new feature so pressing shift while taking a screenshot gives you a 240x224 bitmap.
* Fix fullscreen mode so it changes the resolution of the monitor and makes fullscreen fast again on slower computers.
* Add --swrenderer (-w) flag which will force SDL to use software rendering
* Add --novsync (-v) flag which disables waiting for VSYNC when using accelerated rendering
* Combine Jubatian's scanline optimization (fewer conditionals) with Uze's 720px wide render scaling trick with my arbitrary rescaling using a texture trick. It allows for arbitrary rescaling using both hardware and software renderers, while remaining fast on a 2.0 GHz Core 2.

Improve the SDL2 port

---

tools/uzem/Makefile
tools/uzem/avr8.cpp
tools/uzem/avr8.h
tools/uzem/uzem.cpp

I found it easier to manually merge the changes that andrewm1973 made for his instruction pre-decoder optimization, and they include the following commits he made:
* encoded 32 bit instructions (STS LDS CALL JUMP) to have the 16 bit K from word2 in arg2 of the pre-decoded flash table
* fixed get_insn_size
* Removed reading of the undecoded instruction from the main loop which should free some cache
* Packed Structure for the pre-decoded instructions
* Added pre-decoded arguments
* initial work on the pre decoder to speed up the AVR8 emulation
on his https://github.com/andrewm1973/uzebox/commits/uzem140-fast-pre-decode branch

Manual merge of andrewm1973's instruction pre-decoder

---

kernel/uzeboxCore.c

This prevents the compiler/linker from removing the necessary .init7
and .init8 sections when compiling games that have:
COMMON = -mmcu=$(MCU) -flto -fwhole-program
in their Makefile.
Without the "used" attribute, the linker will remove those sections,
breaking the game.

Add "used" attribute to wdt_init and Initialize

---

tools/uzem/uzem.cpp

Lowering the filename prevents loading files that contain upper case letters in filenames.
Use strncasecmp when comparing file ending instead.

Don't lower the filename when loading hex or uze file

---

kernel/sdBase.h

This fixes compiling errors which occur if sdBase.h is included before an
other include which provides stdint.h whose types it uses.

Bugfix: Added include for stdint.h to kernel/sdBase.h

---

tools/gconvert/gconvert.cpp

It works similar to maps.
For example, adding this section to the xml:
```
<defines>
<define def-name="SKY_TILE" left="0" top="10"/>
<define def-name="ARROW_TILE" left="10" top="0"/>
<define def-name="PAINTED_TILE" left="11" top="0"/>
<define def-name="PERIOD_TILE" left="14" top="0"/>
<define def-name="HIT_TILE" left="3" top="10"/>
<define def-name="NON_FIRE_TILE" left="1" top="11"/>
<define def-name="FIRE_TILE" left="2" top="11"/>
<define def-name="CRACK_TILE" left="3" top="11"/>
<define def-name="T_TILE" left="0" top="13"/>
<define def-name="B_TILE" left="1" top="13"/>
<define def-name="L_TILE" left="2" top="13"/>
<define def-name="R_TILE" left="3" top="13"/>
<define def-name="TL_TILE" left="4" top="13"/>
<define def-name="BL_TILE" left="5" top="13"/>
<define def-name="BR_TILE" left="6" …
```

gconvert: Tile defines

---

demos/Bootloader/bootloaderCore.s
demos/Bootloader/mmc.s
demos/Megatris/asmFunctions.s
demos/tutorialSD/mmc.s
kernel/mmc.s
kernel/sdBase.S
kernel/soundMixerInline.s
kernel/soundMixerVsync.s
kernel/uzeboxVideoEngineCore.s
kernel/videoMode1/videoMode1.s
kernel/videoMode10/videoMode10.s
kernel/videoMode13/videoMode13core.s
kernel/videoMode2/videoMode2.s
kernel/videoMode3/videoMode3core.s
kernel/videoMode5/videoMode5.s
kernel/videoMode6/videoMode6.s
kernel/videoMode7/videoMode7.s
kernel/videoMode9/videoMode9core.s

Newer gcc versions (6.2.0) don't like the way bytes are allocated in the bss and will refuse to compile.
See here: http://uzebox.org/forums/viewtopic.php?f=3&t=2371&p=18023#p18023
I replaced all .byte 1 occurrences in .bss by .space 1
.word 1 by .space 2
.long 1 by .space 4
All demos compile and I tested a mode 3 game with success. Another set of eyes to catch possible mistakes would be nice.

Properly allocate bytes in the bss

---

demos/BootDemo/BootDemo.c
demos/BootDemo/default/Makefile
demos/BootDemo/gameinfo.properties
kernel/bootlib.h
kernel/bootlib.s

This API library enables using SDHC cards and FAT32 filesystems with
fragmentation through the V.5.x.x bootloader if it is available (otherwise
reverting to an MMC and FAT16 implementation).
The demo shows off the basic features of this library, also doubling as an
useful program for querying SD cards.

Bootloader API library added with a demo.

---

tools/uzem/SDEmulator.cpp

When compiling on Mac OSX "error: ordered comparison between pointer and zero" is encountered. This PR should be tested on Windows and Linux before merging.

Fix 'ordered comparison between pointer and zero'

---

kernel/uzebox.h
kernel/uzeboxVideoEngineCore.s
kernel/videoMode3/videoMode3.c

Games relying on GetVsyncCounter() for world time should be able to save the value when the game is paused, and then restore it after the game is unpaused by calling SetVsyncCounter() to prevent world time from advancing while paused.
Changes:
- Add global SetVsyncCounter ASM function and C prototype
- Fix compiler warning when SPRITES_AUTO_PROCESS=0
Testing:
- Tested against default ROMS, additional Mode 3 games.

Add SetVsyncCounter function, fix compiler warning when SPRITES_AUTO_PROCESS=0

---

tools/midiconv/src-programs/midiconv.cpp

Summary:
- Incorrect logic was being used to test for a note off event, causing the else if statement that handled program change events after it to not fire. As a result, program change events beyond the first were not included in the output.
Changes:
- Fix the logic that tests for note off events
Testing:
- Compared the output against the previous version, and with a MIDI containing many program change events (thanks D3thAdd3r!).
- Also compared it against the old Java MidiConvert program. Output is now nearly identical to the old Java version after running the result of midiconv through mconvert to compress it further for the streaming engine.

Fix midiconv incorrect handling of program change events

---

demos/Whack-a-Mole/gameinfo.properties
tools/packrom/packrom.cpp
tools/uzem/uzerom.cpp
tools/uzem/uzerom.h

Eliminated the .uze format "mouse" variable, as it was unused anywhere.
Used this, plus 1 more reserved byte for a peripheral support/default bit matrix. Added support for this more expandable format to Packrom and Uzem.
This is very important for peripheral adoption/support, because it minimizes the complexity of using peripherals in emulation. In addition it easily support more peripherals.
Essentially, for each peripheral, on a per game basis, the device can be "supported" which means the program optionally will work it it(but leave off by default), and "default" which means if this peripheral is an option, it is clearly preferred to use it(ie Whack a Mole game). This is used by the emulator, to present the user with an ideal emulation state from the start, instead of having to lookup …

.uze peripheral support/defaults

---

tools/packrom/packrom.cpp
tools/uzem/uzem.cpp

Summary:
- This PR: https://github.com/Uzebox/uzebox/pull/110/files was abandoned, but its replacement was missing the required code change to uzem.cpp
Changes:
- This adds the original changes to uzem.cpp, and a change to packrom.cpp to remove a commented out line.
Testing:
- make clean
- make
- uzem builds and runs properly

Fix compile error (the new PR was missing a file)

---

tools/packrom/packrom.cpp
tools/uzem/avr8.cpp
tools/uzem/avr8.h
tools/uzem/uzem.cpp
tools/uzem/uzerom.cpp
tools/uzem/uzerom.h

Made packrom and Uzem additions to support arbitrary rotation/mirroring to match various possible arcade cabinet layouts. This allows the .uze file to automatically specify a particular rotation to use. This is expected to make JAMMA ROMs which aren't feasible to play in emulation currently, work transparently to the user(this behavior can be overridden with flags).
Method used should be basically no speed loss, and should work in any environment? Tested Linux Windowed of any size and full screen. Plan to extend these same options to CUzebox once discussed/modified/approved.

JAMMA Additions

---

demos/Megatris/Megatris.c

Fixes insta-topout bug reported in #128.

Megatris: fixing insta-topout bug when pressing Hold key when a piece is locking in

---

demos/BcDash/default/Makefile
demos/DonkeyKong/default/Makefile
demos/Frogger/default/Makefile
demos/PacMan/default/Makefile
demos/SPIRamMusicDemo/default/Makefile
demos/SpaceInvaders/default/Makefile
demos/Zombienator/default/Makefile
tools/gconvert/Makefile
tools/packrom/Makefile
tools/uzem/Makefile

I tweaked some makefiles and now the Uzebox repo buillds under FreeBSD (tested under v14) and Haiku (tested under beta4).
To build the repo:
FreeBSD / GhostBSD
pkg install gmake gcc sdl2 os-generic-userland-devtools avr-gcc avr-libc
<clone repo, cd uzebox>
gmake
Haiku
pkgman install avr_gcc avr_libc libsdl2_devel
<clone repo, cd uzebox>
make
EDIT 27th June 2024
This PR now also includes pcm2hex for converting audio files for use in Uzebox programs.

Add support for building repo with FreeBSD and Haiku

---

kernel/videoMode5/videoMode5.c

The call to ProcessFading() was commented out.  Because of this all calls to FadeIn()/FadeOut() with a speed > 0 in Mode 5 resulted in a complete hang.
Looking at the source code, Mode 10 should have the same problem, but as I've only found this bug and verified this fix under Mode 5, I did not include a fix for Mode 10.
I've already posted this on the Uzebox forums – this is by no means a "work faster to fix this" reminder ;-)
I need this fix in a repository so that I can refer to it in the build instructions of Uzepede. After creating my fork of the Uzebox repo and comitting this fix, opening the Pull Request was just a click away, so here we are.

fix FadeIn() and FadeOut() in Mode 5

---

tools/gconvert/Makefile
tools/packrom/Makefile
tools/uzem/Makefile

There are several vintage computer platforms where NetBSD is often your only choice if you want to run a modern OS so I have made the few small changes that were required to get the Uzebox repo to build successfully under NetBSD 10.0.
The following NetBSD command can be used to install all of the required build dependencies
`pkgin install git gcc14 avr-gcc avr-libc gmake SDL2`
After installing those and cloning the Uzebox repo, the user only has to run `gmake` to build the repo.

Add NetBSD support

---

demos/sdspiram/sdspiram.c
kernel/spiram.h
kernel/spiram.s

Detection supports the following chip sizes: 128K, 256K, 512K, 1M, 2M, 4M and 8M. The library was intended for chips having 3 address bytes, hence the smallest size supported is 128Kbytes.

New init function for the SPI RAM library to allow for detecting SPI RAM size
